add base readme file
MIT-Emerging-Talent/ET6-foundations-group-25 pull request #12
Opened 2024-12-31 12:57 UTC by kefahalshaer

2024-12-31 16:39 UTC, Tbaosman requested changes

2024-12-31 16:39 UTC, Tbaosman commented on .vscode/settings.json
It seems that you didn't sync your branch with the main one, type git pull in your terminal

2024-12-31 16:39 UTC, Tbaosman commented on README.md
I think the Main repository README should be somehow abstract, and may include but not be limited to:

- Quick Overview(Which you've already done)
- Repo structure and purpose 

...

2024-12-31 18:46 UTC, mohd-makki commented on .vscode/settings.json
shall we now start push our program from our local to the github repo or just give an idea about the project want to be created

2024-12-31 21:52 UTC, Tbaosman commented on .vscode/settings.json
you should first make an issue, added it the project board and then create a branch and work on it @mohd-makki

2025-01-08 16:06 UTC, Tbaosman approved these changes
All seems good now. Nice work!

2025-01-08 16:12 UTC, merged